package com.example.shared.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.index.CompoundIndex;

import java.time.LocalDateTime;
import java.util.List;
import java.math.BigDecimal;

/**
 * Order entity representing a purchase order in the e-commerce platform.
 * Stored in MongoDB collection "orders".
 */
@Document(collection = "orders")
@CompoundIndex(name = "buyerId_createdAt_idx", def = "{'buyerId': 1, 'createdAt': -1}")
@CompoundIndex(name = "sellerId_createdAt_idx", def = "{'items.sellerId': 1, 'createdAt': -1}")
@CompoundIndex(name = "status_createdAt_idx", def = "{'status': 1, 'createdAt': -1}")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Order {

    @Id
    private String id;

    @Indexed
    private String buyerId;

    private List<OrderItem> items;

    private BigDecimal totalPrice;

    private BigDecimal shippingCost;

    @Indexed
    private OrderStatus status;

    private PaymentMethod paymentMethod;

    private String shippingAddress;

    private String trackingNumber;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    private LocalDateTime estimatedDeliveryDate;

    private LocalDateTime deliveredAt;

    private String notes;

    // Getters & Setters (will be generated by Lombok @Data)
    // Constructors (will be generated by Lombok @AllArgsConstructor and @NoArgsConstructor)

    @Override
    public String toString() {
        return "Order{" +
                "id='" + id + '\'' +
                ", buyerId='" + buyerId + '\'' +
                ", status=" + status +
                ", totalPrice=" + totalPrice +
                ", createdAt=" + createdAt +
                '}';
    }
}
